language: python
python:
    - "2.7"

sudo: required

# Travis build script for RenPy
# based on Monika-After-Story script.
  
# This is the install stage
# All your dependencies go here. We have done the RenPy SDK part done for you.

install:
    - rsync -av --progress * game --exclude game --exclude .travis

    - cd ..

    - bash ./aliceos/.travis/pull_resource.sh

    - mkdir -p mod/
    
    - cp -vRf aliceos/* mod/
    
    - bash aliceos/.travis/inject_version.sh

    - bash aliceos/.travis/inject_compile_target.sh
    
    - cd renpy


env:
    # this is required as there was build issues without this, don't remove this.
    - SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy DIST_TARGET=ddlc
    - SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy DIST_TARGET=latest

# This is the script part. This is where the actual building is happening.
# This produces an artifact which we'll use later on to publish a release.

script: ./renpy.sh "../mod/" lint && ./renpy.sh launcher distribute "../mod/" && cd ..


# This is where the actual releases happen. Travis has the ability to publish releases from GitHub, Amazon S3, OpenShift, etc.
# Read on https://docs.travis-ci.com/user/deployment/releases/ to learn more
# For this type of configuration, we're using the GitHub releases schema

deploy:
  provider: releases
  api_key:
    # DO NOT CHANGE THIS! Travis can replace this since it's a Environment Variable.
    # Head to Settings > Environment variables and set this.
    secure: $GITHUB_API_KEY
  file_glob: true
  file: "*-dists/*-$DIST_TARGET.zip"
  skip_cleanup: true
  on:
    tags: true # your mods only builds and uploads releases on a GitHub Git tag so make sure you tag and release accordingly!